version: '3.8'

services:
  web:
    build: .
    command: python yatube/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/app
    ports:
    - 8000:8000
    environment:
      SECRET_KEY: eszwq@$h6x7o&i_fvoay!7pvny*n052(p0o@0m%2r3k1r-io01
    depends_on:
      - db
  db:
    image: postgres:11.10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
  postgres_data: